version: '3.8'
services:
  test_db:
    build: .
    ports:
      - 3306:3306
    environment:
      - TEST_DB_HOST=localhost
      - TEST_DB_PORT=3306
      - MYSQL_ROOT_PASSWORD=testRootPass
      - MYSQL_USER=testApiUser
      - MYSQL_PASSWORD=testApiUserPass
      - MYSQL_DATABASE=testdb
