name: PR Tests and Builds

on:
  pull_request:
    branches: [ main ]

env:
  TEST_DB_HOST: localhost
  TEST_DB_PORT: 3306
  MYSQL_ROOT_PASSWORD: testRootPass
  MYSQL_USER: testApiUser
  MYSQL_PASSWORD: testApiUserPass
  MYSQL_DATABASE: testdb

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Initialise Docker Test Db
      working-directory: ./api/deployment_scripts/
      run: ./test_db_start.sh

    - name: Setup Dependencies
      working-directory: ./api
      run: npm install

    - name: Run Test
      working-directory: ./api
      run: npm run test

    - name: Docker Build
      run: docker build ./api --tag dumitruvulpe/team2ip:latest
