name: Frontend PR Tests and Builds

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Installing NPM Dependencies
        working-directory: ./web
        run: npm install
      
      - name: Ng Test
        working-directory: ./web
        run: npm run test:ci

      - name: Docker Build 
        run: docker build ./web --tag dumitruvulpe/team2ip-web:latest
